name: Deploy docs

inputs:
  token:
    description: "GitHub access token"
    required: true

outputs:
  url:
    description: Deployment URL
    value: ${{ steps.deployment.outputs.page_url }}

runs:
  using: "composite"

  steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
